import {
  GalleryItem,
  SmsLog,
  SponsorshipRecord,
  StudentProfile,
} from "@/types";

export const totalStudentCount = 60;

export const students: StudentProfile[] = [
  {
    id: "st-001",
    nickname: "한빛",
    gender: "여",
    grade: "중2",
    description: "음악 활동을 좋아하고, 친구들과 합창을 즐기는 학생입니다.",
    profileTheme: "from-[#ffd9b8] to-[#ffeede]",
    letterSummary: "이번 학기에는 과학 탐구 동아리에 들어가고 싶어요.",
    sponsorshipStatus: "available",
  },
  {
    id: "st-002",
    nickname: "바다",
    gender: "남",
    grade: "중3",
    description: "기숙사 생활에 적응하며 축구와 영어 회화를 열심히 배우고 있습니다.",
    profileTheme: "from-[#d7ebff] to-[#eef7ff]",
    letterSummary: "후원해주시면 생활관비 부담을 줄이고 공부에 집중할 수 있어요.",
    sponsorshipStatus: "pending",
  },
  {
    id: "st-003",
    nickname: "새봄",
    gender: "여",
    grade: "고1",
    description: "디자인과 미술에 관심이 많고 학교 행사 포스터 제작을 맡고 있습니다.",
    profileTheme: "from-[#ffe5ec] to-[#fff2f6]",
    letterSummary: "저의 꿈은 아이들을 위한 디자이너가 되는 것입니다.",
    sponsorshipStatus: "matched",
  },
  {
    id: "st-004",
    nickname: "누리",
    gender: "남",
    grade: "고2",
    description: "수학을 좋아하고, 동생들을 도와주는 멘토 역할을 하고 있습니다.",
    profileTheme: "from-[#f7edc4] to-[#fff7d9]",
    letterSummary: "작은 응원이 큰 힘이 된다는 걸 매일 느끼고 있어요.",
    sponsorshipStatus: "available",
  },
  {
    id: "st-005",
    nickname: "하랑",
    gender: "여",
    grade: "중1",
    description: "책 읽기와 글쓰기를 좋아하며 학교 소식지를 만드는 데 참여합니다.",
    profileTheme: "from-[#d9f0e4] to-[#eefaf3]",
    letterSummary: "읽은 책 이야기를 친구들에게 들려주는 시간이 가장 좋아요.",
    sponsorshipStatus: "matched",
  },
  {
    id: "st-006",
    nickname: "도담",
    gender: "남",
    grade: "고3",
    description: "진로를 준비하며 방과 후 학습에 꾸준히 참여하고 있는 학생입니다.",
    profileTheme: "from-[#dfe6ff] to-[#f1f4ff]",
    letterSummary: "대학 진학 준비를 위해 공부 시간을 늘리고 있습니다.",
    sponsorshipStatus: "pending",
  },
  {
    id: "st-007",
    nickname: "시온",
    gender: "여",
    grade: "중2",
    description: "밝은 성격으로 친구들의 고민을 잘 들어주는 학생입니다.",
    profileTheme: "from-[#ffe0cb] to-[#fff0e4]",
    letterSummary: "언젠가는 상담사가 되어 도움이 되는 사람이 되고 싶어요.",
    sponsorshipStatus: "available",
  },
  {
    id: "st-008",
    nickname: "하늘",
    gender: "남",
    grade: "고1",
    description: "영상 촬영 동아리에서 학교 행사를 기록하고 있습니다.",
    profileTheme: "from-[#d8f3ff] to-[#edf9ff]",
    letterSummary: "학교 이야기를 기록하는 일을 계속하고 싶습니다.",
    sponsorshipStatus: "matched",
  },
];

export const sponsorships: SponsorshipRecord[] = [
  {
    id: "sp-240501",
    studentId: "st-002",
    sponsorName: "김민서",
    sponsorPhone: "010-1245-9981",
    sponsorEmail: "minseo@example.com",
    sponsorshipType: "정기후원",
    sponsorshipPeriod: "12개월",
    sponsorPublic: true,
    sponsorMessage: "하루하루 건강하게 성장하길 응원합니다.",
    receiptRequested: true,
    status: "입금대기",
    createdAt: "2026-05-11 14:22",
  },
  {
    id: "sp-240502",
    studentId: "st-003",
    sponsorName: "이정현",
    sponsorPhone: "010-2299-8842",
    sponsorEmail: "jung@example.com",
    sponsorshipType: "일시후원",
    sponsorshipPeriod: "1회",
    sponsorPublic: true,
    sponsorMessage: "꿈을 향한 발걸음을 진심으로 응원합니다.",
    receiptRequested: false,
    status: "입금완료",
    createdAt: "2026-05-10 09:05",
  },
  {
    id: "sp-240503",
    studentId: "st-004",
    sponsorName: "박서연",
    sponsorPhone: "010-5422-1204",
    sponsorEmail: "seoyeon@example.com",
    sponsorshipType: "정기후원",
    sponsorshipPeriod: "6개월",
    sponsorPublic: false,
    sponsorMessage: "편안한 기숙사 생활을 응원해요.",
    receiptRequested: false,
    status: "취소",
    createdAt: "2026-05-08 18:11",
  },
  {
    id: "sp-240504",
    studentId: "st-006",
    sponsorName: "최도윤",
    sponsorPhone: "010-9910-2208",
    sponsorEmail: "doyoon@example.com",
    sponsorshipType: "정기후원",
    sponsorshipPeriod: "3개월",
    sponsorPublic: true,
    sponsorMessage: "수험 생활을 든든하게 돕고 싶습니다.",
    receiptRequested: true,
    status: "입금대기",
    createdAt: "2026-05-12 11:42",
  },
  {
    id: "sp-240505",
    studentId: "st-001",
    sponsorName: "정하은",
    sponsorPhone: "010-7731-4092",
    sponsorEmail: "haeun@example.com",
    sponsorshipType: "일시후원",
    sponsorshipPeriod: "1회",
    sponsorPublic: true,
    sponsorMessage: "학교 생활의 작은 도움이 되길 바랍니다.",
    receiptRequested: false,
    status: "입금완료",
    createdAt: "2026-05-09 15:24",
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "ga-101",
    title: "봄 학기 기숙사 생활 모습",
    type: "image",
    fileLabel: "IMG_2026_0510",
    createdAt: "2026-05-10",
  },
  {
    id: "ga-102",
    title: "주말 독서 프로그램",
    type: "image",
    fileLabel: "IMG_2026_0506",
    createdAt: "2026-05-06",
  },
  {
    id: "ga-103",
    title: "문화 체험 활동 스케치",
    type: "video",
    fileLabel: "VID_2026_0501",
    createdAt: "2026-05-01",
  },
  {
    id: "ga-104",
    title: "학교 행사 준비 현장",
    type: "image",
    fileLabel: "IMG_2026_0428",
    createdAt: "2026-04-28",
  },
  {
    id: "ga-105",
    title: "동아리 발표회 하이라이트",
    type: "video",
    fileLabel: "VID_2026_0424",
    createdAt: "2026-04-24",
  },
  {
    id: "ga-106",
    title: "공동체 활동 기록",
    type: "image",
    fileLabel: "IMG_2026_0421",
    createdAt: "2026-04-21",
  },
];

export const smsLogs: SmsLog[] = [
  {
    id: "sms-001",
    phone: "010-1245-9981",
    templateName: "신청완료_안내",
    status: "성공",
    responseMessage: "전송 완료",
    createdAt: "2026-05-12 11:45",
  },
  {
    id: "sms-002",
    phone: "010-9910-2208",
    templateName: "전화예정_안내",
    status: "성공",
    responseMessage: "전송 완료",
    createdAt: "2026-05-12 11:46",
  },
  {
    id: "sms-003",
    phone: "010-5422-1204",
    templateName: "입금완료_안내",
    status: "실패",
    responseMessage: "수신번호 오류",
    createdAt: "2026-05-12 12:00",
  },
];

export const adminContacts = [
  "010-3024-1188",
  "010-8892-4471",
  "010-7162-3384",
];

export const donationUsage = [
  { label: "학생 생활관비", value: 70 },
  { label: "교육 활동 지원", value: 20 },
  { label: "운영 지원", value: 10 },
];

export const publicSponsorMessages = sponsorships
  .filter((item) => item.sponsorPublic)
  .map((item) => ({
    id: item.id,
    message: item.sponsorMessage,
    sponsorName: item.sponsorName.slice(0, 1) + "*",
  }));
